name: apply2
on: workflow_dispatch

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Get workflow runs
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          WORKFLOW_ID=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs" \
            | jq -r --arg commit "$COMMIT_SHA" '.workflow_runs[] | select(.head_sha == $commit and .path == ".github/workflows/plan.yml").workflow_id')
      - name: print workflow id 
        run: echo $WORKFLOW_ID
