name: Second Workflow
on: workflow_dispatch

jobs:
  get-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Get workflow runs
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs"
