name: plan
on: push

jobs:
  get-runs:
    runs-on: ubuntu-latest
    steps:
      - name: artifact
        run: echo lalal >file

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-file-${{ github.sha }}
          path: file
          retention-days: 1
